### ISSUE TITLE
Suggested accessibility/SEO improvements

### ISSUE THREAD

**Issue by BytewaveMLP** [Reboot01/Reboot01.github.io#1]
A [Google Lighthouse](https://developers.google.com/web/tools/lighthouse) audit of this site suggests a number of improvements for search engine optimization and user accessibility:

- `html` should have a `lang` attribute of `en` since the page is in English
- Add some `meta` tags, like `name="viewport"` and document description tags (OpenGraph, `name="description"`, etc)
- Add `rel="noopener"` to your `a` tags with `href`s to external sites for security reasons, to prevent the opened page having access to [`window.opener`](https://developer.mozilla.org/en-US/docs/Web/API/Window/opener)

**Comment by Reboot01** [comment]
I added the new improvements.
